services:
  - type: web
    name: studio-by-azzi
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    disks:
      - name: data
        mountPath: /opt/render/project/src/server/data
        sizeGB: 1
    envVars:
      - key: ADMIN_TOKEN
        sync: false  # set in Render dashboard
      - key: ALLOWED_ORIGINS
        value: ""     # leave empty for same-origin
      - key: OPENAI_API_KEY
        sync: false  # optional for AI chat
      - key: AI_MODEL
        value: gpt-4o-mini
      - key: ADMIN_EMAIL
        sync: false  # optional SMTP
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
